name: Package sources
on:
  push:
    branches:
      - master

jobs:
  linux:
    name: Package sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v12
      - name: Build
        run: |
          nix-build -A sawtooth-haskell-protos-src
          # echo "::set-output name=result::$(realpath result)"
          cp -r $(realpath result) sawtooth-haskell-protos-src
          tar cvzf sawtooth-haskell-protos-src.tar.gz sawtooth-haskell-protos-src
          rm result
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: sawtooth-haskell-protos-src.tar.gz
      - name: Build sources
        run: |
          nix-build -A sawtooth-haskell-protos-src
          cp -r $(realpath result) sawtooth-haskell-protos-src
          tar cvzf sawtooth-haskell-protos-src.tar.gz sawtooth-haskell-protos-src
      - name: Build docs
        run: |
          nix-build -A build.doc
          cp -r $(realpath result-doc)/share/doc/sawtooth-haskell-protos-0.0.0/html docs
          tar cvzf docs.tar.gz docs
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          # prerelease: true
          # title: ""
          files: |
            sawtooth-haskell-protos-src.tar.gz
            docs.tar.gz
      - name: Deploy docs
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
